# THIS FILE IS FOR HARD-CODED SETTINGS THAT
# CAN'T BE CHANGED BY THE USER
# Set during development and then fixed

# Basic settings
title:                        "Website by Convincible" # Don't need to change this - will be overridden


# Site settings
uid:
  gtm:                        ""
  pin:                        ""
  wot:                        ""
  gmaps:                      ""


# Theme
brand:
  color-1:                    "#ff6633"
  color-2:                    ""
  color-3:                    ""
  color-4:                    ""
  color-5:                    ""
  color-6:                    ""
  bg:                         "#ffffff"
  text:                       "#000000"
  text-reverse:               "#ffffff"


# Define core layouts
layouts:
  primary:                    'page'


# Asset folders
folders:
  assets:                     "/assets"
  css:                        "/assets/css"
  js:                         "/assets/js"
  img:                        "/assets/img"


# Build settings
source:                       "/source"
destination:                  "/public"
include:
- "_redirects"
exclude:
- "/assets" # managed by Grunt
#keep_files:                  # Don't clear from public
#- public/assets


# Collections
collections:
  root:
    output:                   true
    permalink:                "/:name"
  pages:
    output:                   true
    permalink:                "/:path"


# Defaults
defaults:
  - scope:
      path:                   "_pages"
    values:
      layout:                 "page"

permalink:                    ":slug.html"


# Markdown
markdown:                     "kramdown"
kramdown:
  auto_id_prefix:             "h-"
  auto_ids:                   true
  auto_id_stripping:          true
  entity_output:              "symbolic"
  hard_wrap:                  false
  header_offset:              1
  smart_quotes:               "lsquo,rsquo,ldquo,rdquo"
  toc_levels:                 "1..2"
  transliterated_header_ids:  true
  show_warnings:              false
# show_drafts:                null
# future:                     false
# unpublished:                false
excerpt_separator:            "\n\n"
strict_front_matter:          true
