# THIS FILE IS FOR HARD-CODED SETTINGS THAT
# CAN'T BE CHANGED BY THE USER
# Set during development and then fixed

# Basic settings
title:                         "Website by Convincible" # Don't need to change this - will be overridden
url:                           "//localhost:4000"
#content:
#   format:                     "markdown" # or HTML if WYSIWYG -- metadata is always YAML


I18n: # Internationalisation settings
   missing: # What happens when a page is defined in some languages but not others?
      force: false
      # false = do not create a page if language missing
      # true = create all pages in all languages, using slugs from first available language
      repeat: false
      # if force = true
      # false = missing language pages simply offer links to other languages
      # true = missing language pages duplicate content from first available language
      links: true
      # if force = false
      # false = links to unavailable languages show as text only
      # true = links to unavailable languages go directly to first available language
      parents: true
      # if force = false
      # false = parents unavailable in the same language are collapsed
      # true = empty folders for missing parents using first available language for slugs
   dir: # Manually define the direction to be used in given languages if not ltr
      ar: rtl
      zh: auto

# Site settings
uid:
   gtm:                        ""
   pin:                        ""
   wot:                        ""
   map:                        ""


# Theme
brand:
   colors:                     # Array of colors
      -  color:                "ff6633" # Primary color defined first
      #  text:                 # Each color may define a complementary text color
      #  dark:                 # Plus subcolors called light or dark
      #  light:                # which in turn must be a color array increasing in light/dark-ness
      #  -  color:
      #     text:              # ...which in turn may define a text color
      -  color:                "b1c2d3"
      -  color:                "ffffff" # Last in array assumed to be the bg color
         text:                 "000000"
   font:                       # CSS stacks
      body:
         -  "Arial"
         -  "Tahoma"
         -  "Verdana"
         -  "Segoe"
         -  "sans-serif"
      head:
         -  "Georgia"
         -  "Palatino"
         -  "Times"
         -  "Times New Roman"
         -  "serif"


# Formats
images:
   thumb:
      w:                       320
      h:                       180
      fit:                     "'@#~[}{}><>?-+=&^;  _crop"
      crop:                    'ed"ges'
      auto:                    "compress"
      fm:                      "pjpg"
      q:                       50
   hero:
      w:                       1280
      h:                       720
      fit:                     "max"
      auto:                    "compress"
      fm:                      "pjpg"
      q:                       60
   body:
      max-w:                   800
      max-h:                   800
      fit:                     "clip"
      auto:                    "compress"
      fm:                      "pjpg"
      q:                       70
   logo:
      w:                       320
      h:                       180
      fit:                     "clip"
      auto:                    "compress"
      fm:                      "png"
video: # For embeds
   youtube:
      plain:
         modestbranding:          1
         showinfo:                0
         rel:                     0
         cc_load_policy:          0
         iv_load_policy:          3


# Asset folders
assets:
   folders:
      assets:                  "/assets"
      css:                     "/assets/css"
      js:                      "/assets/js"
      img:                     "/assets/img"
   features:                   # Array of features by name, and whether they have accompanying assets
      form:
         css:                  true
         js:                   false
      video:
         css:                  true
         js:                   true
   layouts:                    # Array of layouts by name, and whether they have accompanying assets
      #service:
         #css:                  true
         #js:                   true
         #features:????


# Build settings
source:                        "source" # NO LEADING SLASH!!!
destination:                   "public"
include:
-  "_redirects"
exclude:
   -  "*.partial.*"
#  -  ""
show_warnings:                 false
#  show_drafts:                null
#  future:                     false
#  unpublished:                false
strict_front_matter:           true


# Collections
collections:
   root:
      output:                  true
      permalink:               "/:name" # flatten any folders here
   pages:                      # This collection is used for basically every page on the site
      output:                  true
      permalink:               "/:path" # respect folder structure here


# Defaults
defaults:
   -  scope:
         path:                 "_pages" # All pages on the site stored here
      values:
         layout:               "html/article"

permalink:                     ":slug.html"

excerpt_separator:             "" # Do not generate excerpts - currently this is inefficient as Jekyll renders entire page twice

# Markdown
markdown:                      "kramdown"
kramdown:
   auto_id_prefix:             "section-"
   auto_ids:                   true
   auto_id_stripping:          true
   entity_output:              "symbolic"
   hard_wrap:                  false
   header_offset:              1
   smart_quotes:               "lsquo,rsquo,ldquo,rdquo"
   toc_levels:                 "1..2"
   transliterated_header_ids:  true
