# THIS FILE IS FOR HARD-CODED SETTINGS THAT
# CAN'T BE CHANGED BY THE USER
# Set during development and then fixed

# Basic settings
title:                        "Website by Convincible" # Don't need to change this - will be overridden


# Site settings
uid:
  gtm:                        ""
  pin:                        ""
  wot:                        ""
  gmaps:                      ""


# Theme
brand:
  colors:                     # Array of colors
    - color:                  "ff6633"
    # text:                   # Each color may define a complementary text color
    # dark:                   # Plus a subcolor called light or dark
    # light:                  # which in turn must be a color array
    # - color:
    #   text:                 # ...which in turn may define a text color
    - color:                  "ffffff" # Last in array assumed to be the bg color
      text:                   "000000"
  font:
    head:
      - "Tahoma"
      - "Verdana"
      - "Segoe"
      - "sans-serif"
    body:
      - "Tahoma"
      - "Verdana"
      - "Segoe"
      - "sans-serif"

# Define core layouts
templates:
  primary:                    "page"


# Asset folders
folders:
  assets:                     "/assets"
  css:                        "/assets/css"
  js:                         "/assets/js"
  img:                        "/assets/img"


# Build settings
source:                       "source" # NO LEADING SLASH!!!
destination:                  "public"
#include:
#- ""
#exclude:
#- ""
#- ""


# Collections
collections:
  root:
    output:                   true
    permalink:                "/:name"
  pages:
    output:                   true
    permalink:                "/:path"


# Defaults
defaults:
  - scope:
      path:                   "_pages"
    values:
      layout:                 "page"

permalink:                    ":slug.html"


# Markdown
markdown:                     "kramdown"
kramdown:
  auto_id_prefix:             "h-"
  auto_ids:                   true
  auto_id_stripping:          true
  entity_output:              "symbolic"
  hard_wrap:                  false
  header_offset:              1
  smart_quotes:               "lsquo,rsquo,ldquo,rdquo"
  toc_levels:                 "1..2"
  transliterated_header_ids:  true
  show_warnings:              false
# show_drafts:                null
# future:                     false
# unpublished:                false
excerpt_separator:            "\n\n"
strict_front_matter:          true
